"""Make persona relationship 1-to-n

Revision ID: 334a1444185e
Revises: 6e8b7ef24062
Create Date: 2026-04-10 09:30:26.437410

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "334a1444185e"
down_revision: Union[str, Sequence[str], None] = "6e8b7ef24062"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('person_personas')
    # op.drop_table('group_personas')
    # with op.batch_alter_table('actions', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'notes', ['note_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table("groups", schema=None) as batch_op:
        batch_op.add_column(sa.Column("persona_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_group_persona", "personas", ["persona_id"], ["id"]
        )

    # with op.batch_alter_table('messages', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'notes', ['note_id'], ['id'], ondelete='CASCADE')

    # with op.batch_alter_table('note_embeddings', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'notes', ['note_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table("persons", schema=None) as batch_op:
        batch_op.add_column(sa.Column("persona_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_person_persona", "personas", ["persona_id"], ["id"]
        )

    # with op.batch_alter_table('references', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'notes', ['source_note_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("references", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "notes", ["source_note_id"], ["id"])

    with op.batch_alter_table("persons", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("persona_id")

    with op.batch_alter_table("note_embeddings", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "notes", ["note_id"], ["id"])

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "notes", ["note_id"], ["id"])

    with op.batch_alter_table("groups", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("persona_id")

    with op.batch_alter_table("actions", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "notes", ["note_id"], ["id"])

    op.create_table(
        "group_personas",
        sa.Column("group_id", sa.INTEGER(), nullable=True),
        sa.Column("persona_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
        ),
    )
    op.create_table(
        "person_personas",
        sa.Column("person_id", sa.INTEGER(), nullable=True),
        sa.Column("persona_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["persons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
        ),
    )
    # ### end Alembic commands ###
