"""Add phase 6 models and fields

Revision ID: 6e8b7ef24062
Revises: c4fd669b903b
Create Date: 2026-04-10 08:16:50.784464

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6e8b7ef24062"
down_revision: Union[str, Sequence[str], None] = "c4fd669b903b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "practise_frameworks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("formatting_preferences", sa.Text(), nullable=True),
        sa.Column("common_phrasing", sa.Text(), nullable=True),
        sa.Column("tone_idioms", sa.Text(), nullable=True),
        sa.Column("principles_tenets", sa.Text(), nullable=True),
        sa.Column("is_core", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("practise_frameworks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_practise_frameworks_id"), ["id"], unique=False
        )

    op.create_table(
        "personas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("avatar_logo", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("framework_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["framework_id"],
            ["practise_frameworks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("personas", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_personas_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_personas_name"), ["name"], unique=False)

    op.create_table(
        "framework_proposals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("aspect", sa.String(), nullable=True),
        sa.Column("action", sa.String(), nullable=True),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("persona_id", sa.Integer(), nullable=True),
        sa.Column("is_core", sa.Boolean(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "ACCEPTED", "REJECTED", name="frameworkproposalstatus"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("framework_proposals", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_framework_proposals_id"), ["id"], unique=False
        )

    op.create_table(
        "group_personas",
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("persona_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
        ),
    )
    op.create_table(
        "person_personas",
        sa.Column("person_id", sa.Integer(), nullable=True),
        sa.Column("persona_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["persons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
        ),
    )

    with op.batch_alter_table("groups", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("custom_framework_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            "fk_groups_framework",
            "practise_frameworks",
            ["custom_framework_id"],
            ["id"],
        )

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("analyzed_for_framework", sa.Boolean(), nullable=True)
        )

    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("analyzed_for_framework", sa.Boolean(), nullable=True)
        )

    with op.batch_alter_table("persons", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("custom_framework_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            "fk_persons_framework",
            "practise_frameworks",
            ["custom_framework_id"],
            ["id"],
        )

    with op.batch_alter_table("references", schema=None) as batch_op:
        batch_op.add_column(sa.Column("url", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("embedding_status", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("analyzed_for_framework", sa.Boolean(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("references", schema=None) as batch_op:
        batch_op.drop_column("analyzed_for_framework")
        batch_op.drop_column("embedding_status")
        batch_op.drop_column("url")

    with op.batch_alter_table("persons", schema=None) as batch_op:
        batch_op.drop_constraint("fk_persons_framework", type_="foreignkey")
        batch_op.drop_column("custom_framework_id")

    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.drop_column("analyzed_for_framework")

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_column("analyzed_for_framework")
        batch_op.drop_column("source")

    with op.batch_alter_table("groups", schema=None) as batch_op:
        batch_op.drop_constraint("fk_groups_framework", type_="foreignkey")
        batch_op.drop_column("custom_framework_id")

    op.drop_table("person_personas")
    op.drop_table("group_personas")
    with op.batch_alter_table("framework_proposals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_framework_proposals_id"))

    op.drop_table("framework_proposals")
    with op.batch_alter_table("personas", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_personas_name"))
        batch_op.drop_index(batch_op.f("ix_personas_id"))

    op.drop_table("personas")
    with op.batch_alter_table("practise_frameworks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_practise_frameworks_id"))

    op.drop_table("practise_frameworks")
    # ### end Alembic commands ###
