"""Add sent_at and check for missing columns

Revision ID: 8afb9f91bb4d
Revises: 15045bb76f5a
Create Date: 2026-04-10 19:01:56.310736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8afb9f91bb4d'
down_revision: Union[str, Sequence[str], None] = '15045bb76f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
    # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_actions_note_id_notes'), 'notes', ['note_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('messages', schema=None) as batch_op:
    # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_messages_note_id_notes'), 'notes', ['note_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('note_embeddings', schema=None) as batch_op:
    # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_note_embeddings_note_id_notes'), 'notes', ['note_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('references', schema=None) as batch_op:
    # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_references_source_note_id_notes'), 'notes', ['source_note_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('references', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_references_source_note_id_notes'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'notes', ['source_note_id'], ['id'])

    with op.batch_alter_table('note_embeddings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_note_embeddings_note_id_notes'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'notes', ['note_id'], ['id'])

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_messages_note_id_notes'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'notes', ['note_id'], ['id'])

    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_actions_note_id_notes'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'notes', ['note_id'], ['id'])

    # ### end Alembic commands ###
