"""add avatar_logo

Revision ID: 8b512c01abcd
Revises: 8afb9f91bb4d
Create Date: 2026-04-19 12:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b512c01abcd'
down_revision: Union[str, Sequence[str], None] = 'ecf170dd3cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_logo', sa.String(), nullable=True))

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_logo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('avatar_logo')

    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_column('avatar_logo')
    # ### end Alembic commands ###
