"""Add attribution columns to framework proposals and update observation count

Revision ID: ecf170dd3cc6
Revises: 44951d1a8908
Create Date: 2026-04-12 07:22:13.533087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecf170dd3cc6'
down_revision: Union[str, Sequence[str], None] = '44951d1a8908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('framework_proposals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_framework_proposals_person_id_persons'), 'persons', ['person_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_framework_proposals_group_id_groups'), 'groups', ['group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('framework_proposals', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_framework_proposals_group_id_groups'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_framework_proposals_person_id_persons'), type_='foreignkey')
        batch_op.drop_column('group_id')
        batch_op.drop_column('person_id')

    # ### end Alembic commands ###
