"""Refactor framework to itemized structure

Revision ID: ee14158fac19
Revises: 8afb9f91bb4d
Create Date: 2026-04-11 08:29:04.431870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee14158fac19'
down_revision: Union[str, Sequence[str], None] = '8afb9f91bb4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practise_framework_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('framework_id', sa.Integer(), nullable=True),
    sa.Column('aspect', sa.String(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['framework_id'], ['practise_frameworks.id'], name=op.f('fk_practise_framework_items_framework_id_practise_frameworks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practise_framework_items'))
    )
    with op.batch_alter_table('practise_framework_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practise_framework_items_id'), ['id'], unique=False)

    with op.batch_alter_table('framework_proposals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observation_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('practise_frameworks', schema=None) as batch_op:
        batch_op.drop_column('formatting_preferences')
        batch_op.drop_column('principles_tenets')
        batch_op.drop_column('tone_idioms')
        batch_op.drop_column('common_phrasing')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practise_frameworks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('common_phrasing', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('tone_idioms', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('principles_tenets', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('formatting_preferences', sa.TEXT(), nullable=True))

    with op.batch_alter_table('framework_proposals', schema=None) as batch_op:
        batch_op.drop_column('observation_count')

    with op.batch_alter_table('practise_framework_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practise_framework_items_id'))

    op.drop_table('practise_framework_items')
    # ### end Alembic commands ###
